### ISSUE TITLE
nav don't close when click on a link

### ISSUE THREAD

**Issue by Corto64** [mac81/pure-drawer#10]
Hi Thomas, 
First, thank's for this great great job and sharing.
I use the "scaleRotate" effect (left), but when i click on a link, the nav element don't close. (It's closed only with a click on the page, or on toggler.)
How to get this? 
Thank's for your answer.

**Comment by Corto64** [comment]
Hi Thomas, and happy new year!
And sorry for my very long response time I wasn't at work...
Thank's for your answer, but i've not event handler attached to my links, and to be certain to eliminate all sources of problems,  i have remove all script (js) and i've the same problem. 
But, i have not specify that i work on a one-page site; when i use this on a multipage, the nav element is closed.
For this moment, i don't see any else solution...
Thank's again for your great job, and your help.
PS: and sorry for my bad english

**Comment by mac81** [comment]
Happy new year!

Because I only use css on Pure Drawer there is no way to close the drawer when using internal linking other than attaching a javascript eventhandler to your project. 

Inside the eventhandler add/remove the 'checked' attribute on the '.pure-toggle' input element.

F.ex if you use jQuery 

$('.the-link-beeing-clicked').on('click', function() {
  $('.pure-toggle').removeAttr('checked');
});

**Comment by Corto64** [comment]
Hello Thomas,
It's just perfect!
Thank you very much!
