### ISSUE TITLE
Multiple drawers in different parent divs 

### ISSUE THREAD

**Issue by rickibarnes** [mac81/pure-drawer#30]
Hey, this is a great and very elegant solution. I'm having a little problem though - as per the title, I'd like to have the drawers in different parent divs.

I actually have it working with everything in the same div, but it's not an ideal set up. To get the toggles where and how I want them to be, I've had to use some pretty ugly code and they're still not perfectly how I'd like them.

With the toggles in the different parent divs, the layout is exactly as I want it, but of course the toggles for each drawer are still visible when the other drawer is active.

I think this is because it all operates on the ~ selector, which makes me think nothing can be done about this, but I thought I'd ask.

Cheers

**Comment by mac81** [comment]
Hi. Thanks for trying out Pure Drawer.

Not sure if I understand your question 100%, but I don't believe that what your trying to achieve is possible with pure css because css doesn't have a 'parent' selector. So the 'pure-pusher-container' needs to be a sibling, child or a child of a sibling of the '.pure-toggle'.

You could of course move the the '.pure-toggle-label' around freely, but the you would not be able to ha an 'checked' styling for it.

Hope this answers your question. If not, maybe provide me with some example of the structure your trying to achieve so I get a better understanding of the issue.

**Comment by rickibarnes** [comment]
Hi, thanks for the reply. It makes me think even more that nothing can be done about my situation, but I've made up a little demo so you can see what I mean: [http://rickibarn.es/groundzero/pure-drawer/](url)

So my right menu is in a different <section> to the top menu, this is what I mean by having different parents. You can see it is very close to still working; it's just that the toggles still appear no matter which menu is active.
